### ISSUE TITLE
Portfaolio

### ISSUE THREAD

**Issue by ConanGH-S** [iLestar/Portafolio#1]
![imagen](https://github.com/iLestar/Portfaolio/assets/80909795/f37517da-ec77-48f9-b025-7cf359451fbb)

**Comment by iLestar** [comment]
![imagen](https://github.com/iLestar/Portafolio/assets/71247432/682215ec-311e-4670-b918-7d879e9f7e59)
Muchas gracias por tu Issue. Ya está corregido el nombre del repositorio.
